# Extra autostart processes
# exec-once = uwsm-app -- my-service
# exec-once = kdeconnectd 
# exec-once = kdeconnect-indicator 
exec-once = gnome-keyring-daemon --start --components=secrets
# exec-once = sleep 2 && kdeconnect-indicator
# exec-once = sleep 2 && GTK_THEME=Adwaita-dark QT_QPA_PLATFORM=xcb QT_QPA_PLATFORMTHEME=gtk3 kdeconnect-indicator

