windowrule = float on, center on, match:tag centered-floating-window
windowrule = tag +centered-floating-window, match:class ^Typra$, match:title ^Print$
windowrule = tag +centered-floating-window, move -411 789, size 862 542, match:class ^org.gnome.clocks$, match:title ^Clocks$
windowrule = tag +centered-floating-window, move -411 789, size 862 542, match:class ^dev.bragefuglseth.Keypunch.Devel$, match:title ^Keypunch$
windowrule = tag +centered-floating-window, move -411 789, size 862 642, match:class ^it.mijorus.gearlever$ 
windowrule = tag +centered-floating-window, move -692 753, size 1419 868, match:class ^kopuz$
windowrule = tag +centered-floating-window, move -411 789, size 862 642, match:class ^spotify.com__-Default$ 

