windowrule = float on, center on, match:tag centered-floating-window
windowrule = tag +centered-floating-window, match:class ^Typra$, match:title ^Print$
windowrule = tag +centered-floating-window, move -411 789, size 862 542, match:class ^org.gnome.clocks$, match:title ^Clocks$
windowrule = tag +centered-floating-window, move -411 789, size 862 542, match:class ^nuclear-music-player$, match:title ^nuclear-music-player$
