# windowrule = float on, center on, match:tag centered-floating-window
windowrule = tag +centered-floating-window, move -411 789, size 862 542, match:class ^org.gnome.clocks$, match:title ^Clocks$
# windowrule = tag +centered-floating-window,move -411 789, size 862 542, match:class ^dev.bragefuglseth.Keypunch.Devel$, match:title ^Keypunch$
windowrule = tag +centered-floating-window, move -411 789, size 862 642, match:class ^it.mijorus.gearlever$ 
# windowrule = tag +centered-floating-window, move -692 753, size 1419 868, match:class ^kopuz$
# # windowrule = tag +centered-floating-window, move -411 789, size 862 642, match:class ^spotify.com__-Default$ 


##kopuz
windowrule {
    name = kopuz-centered
    match:class = ^kopuz$
    float = false
    center = true
    size = 1419 868
    pseudo = true
}

##Keypunch
windowrule {
    name = Keypunch-centered
    match:class = ^dev.bragefuglseth.Keypunch.Devel$
    float = false
    center = true
    size = 1419 868
    pseudo = true
}

##gearlever
windowrule {
    name = gearlever
    match:class = ^it.mijorus.gearlever$
    float = false
    center = true
    size = 1419 868
    pseudo = true
}

windowrule {
    name = firefox-profile
    # match:class = ^firefox-nightly$
    match:title =  ^Nightly - Choose a profile$
    float = true 
    center = true
    size = 900 768
    pseudo = true

  }

# nvtop (Waybar GPU module click via omarchy-launch-or-focus-tui)
# Reuses Omarchy's floating-window tag: float + center + size 875x600
windowrule = tag +floating-window, match:class ^org\.omarchy\.nvtop$

